name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cdk_frontend_deployment:
    name: Deploy CDK Frontend
    environment: prod
    runs-on: ubuntu-latest
    
    permissions: # needed for AWS creds https://github.com/aws-actions/configure-aws-credentials/issues/271#issuecomment-931012696
      id-token: write
      contents: write
      packages: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: 'us-east-1'
          role-to-assume: 'arn:aws:iam::468293815193:role/SSDeploymentRole'

      - name: Compile client code
        env:
          CI: false
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          npm ci
          npm run build
          cd "./cdk"
          npm ci
          cd ..

      - name: CDK Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'MPOS-Calculator-PROD'
          working_dir: './cdk'
          cdk_args: '--require-approval never'